name: nit_helper
description: A CLI tool for building Flutter and Serverpod projects with fvm support.
version: 1.5.0
repository: https://github.com/MaksimLevchenko/nit_helper
environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  args: ^2.4.0
  http: ^1.4.0

executables:
  nit-helper: main

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
