name: nit_helper
description: A CLI for building Flutter and Serverpod projects with optional fvm support.
version: 0.1.0
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  args: ^2.4.0

executables:
  nit-helper: build_tool

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
