name: test_freezed_project
description: Test project for nit-helper with Freezed
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.1

executables:
  test_app:
